### PR TITLE
Add new params for ignore filesystems

### PR DESCRIPTION
**Pull request by kzm0211**
I found a new params for filesystems on "mackerel-agent.conf".
Would you check my PullRequest?

ref: https://mackerel.io/ja/docs/entry/spec/agent

### CODE REVIEW

**Comment by Tomohiro** [comment]
@kzm0211 Thanks for your PR.

Please consider to change the parameter name as `ignore_filesystems` from  just `filesystems`.

And I found this issue for failed test on the Travis CI. Maybe it's bug of the Bundler.
github.com/bundler/bundler/issues/4819
So You don't care about it. It's no problem at all 👍

**Comment by kzm0211** [comment]
@Tomohiro 
Thanks for your reply!
I'll do your proposal as soon as possible.

**Comment by kzm0211** [comment]
@Tomohiro 
I renamed "filesytems" to "ignore_filesystems".
How about this??

**Comment by Tomohiro** [comment]
Thanks!

**Comment by kzm0211** [comment]
Thanks too!
I really appreciate you.

**Pull request merged**
